backend:
  name: git-gateway
  branch: main # Branche principale de ton dépôt

media_folder: "public/images/uploads" # Où les images seront stockées
public_folder: "/images/uploads" # Chemin public pour les images

collections:
  - name: "photos"
    label: "Photos"
    folder: "content/photos"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "image", label: "Image", widget: "image" }
